# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'frankie' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for frankie

  target 'frankie-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

    pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  end

  target 'frankieTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'frankie-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  

end
